/** @deprecated Import from `@/context/accountWallets` instead. */
export {
	assertAccountWalletRoles as assertRequiredFundingAddresses,
	buildVenueAddressChainMap,
	buildVenueAddressChainMap as buildAccountVenueWallets,
	getAccountWalletGate as getRequiredFundingGate,
	isAccountWalletRolesComplete as isRequiredFundingReady,
	isVacmReady,
	isVacmReady as isAccountWalletsReady,
	isTradeFundingReady,
	resolveAccountWalletRoles as resolveRequiredFundingAddresses,
	sorExecutorFundingAddresses,
	sorExecutorWalletRoles,
	SOR_FUNDING_ADDRESSES_STUB,
	SOR_WALLET_ROLES_STUB,
	type VenueAddressChainMap,
	type VenueAddressChainMap as AccountVenueWallets,
	type AccountWalletGate as RequiredFundingGate,
	type AccountWalletRoles as RequiredFundingAddresses,
	type AccountWalletRolesPartial as NormalizedTradingWallets,
	type TradeFundingReady,
	type VenueAddressChainEntry,
	type VenueAddressChainEntry as VenueWallet,
} from "@/context/accountWallets";
